//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilet_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilet
    {
        public int bilet_id { get; set; }
        public Nullable<int> koltuk_no { get; set; }
        public Nullable<int> yolcu_id { get; set; }
        public Nullable<int> sefer_id { get; set; }
        public Nullable<int> indirim_id { get; set; }
        public Nullable<int> bilet_kesen_personel_id { get; set; }
        public Nullable<int> islem_kod { get; set; }
        public string kalkis { get; set; }
        public string varis { get; set; }
        public string satis_tarihi { get; set; }
        public Nullable<decimal> tutar { get; set; }
        public Nullable<int> rezerve { get; set; }
        public Nullable<int> online { get; set; }
        public Nullable<int> iptal { get; set; }
    
        public virtual Indirim_Artis Indirim_Artis { get; set; }
        public virtual Personel Personel { get; set; }
        public virtual Sefer Sefer { get; set; }
        public virtual Yolcu Yolcu { get; set; }
    }
}
