//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilet_Online.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Otobus_BiletEntities : DbContext
    {
        public Otobus_BiletEntities()
            : base("name=Otobus_BiletEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bilet> Bilet { get; set; }
        public virtual DbSet<Guzergah> Guzergah { get; set; }
        public virtual DbSet<Guzergah_Arayol> Guzergah_Arayol { get; set; }
        public virtual DbSet<Guzergah_Tesis> Guzergah_Tesis { get; set; }
        public virtual DbSet<ILLER_MESAFE> ILLER_MESAFE { get; set; }
        public virtual DbSet<Indirim_Artis> Indirim_Artis { get; set; }
        public virtual DbSet<ilceler> ilceler { get; set; }
        public virtual DbSet<iller> iller { get; set; }
        public virtual DbSet<Kodlar> Kodlar { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Otobus> Otobus { get; set; }
        public virtual DbSet<Otobus_Detay> Otobus_Detay { get; set; }
        public virtual DbSet<Otobus_Ozellik> Otobus_Ozellik { get; set; }
        public virtual DbSet<Parametre> Parametre { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Rezerve> Rezerve { get; set; }
        public virtual DbSet<Rol_Servis> Rol_Servis { get; set; }
        public virtual DbSet<Roller> Roller { get; set; }
        public virtual DbSet<Sefer> Sefer { get; set; }
        public virtual DbSet<Sefer_Arayol> Sefer_Arayol { get; set; }
        public virtual DbSet<Servis> Servis { get; set; }
        public virtual DbSet<Tesis> Tesis { get; set; }
        public virtual DbSet<Yolcu> Yolcu { get; set; }
        public virtual DbSet<Kredi_Karti> Kredi_Karti { get; set; }
    }
}
