//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilet_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guzergah_Tesis
    {
        public int guzergah_tesis_id { get; set; }
        public Nullable<int> tesis_id { get; set; }
        public Nullable<int> guzergah_id { get; set; }
        public Nullable<int> mola_suresi { get; set; }
    
        public virtual Guzergah Guzergah { get; set; }
    }
}
