//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilet_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guzergah
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guzergah()
        {
            this.Guzergah_Arayol = new HashSet<Guzergah_Arayol>();
            this.Guzergah_Tesis = new HashSet<Guzergah_Tesis>();
            this.Sefer = new HashSet<Sefer>();
        }
    
        public int guzergah_id { get; set; }
        public string kalkis_yeri { get; set; }
        public string varis_yeri { get; set; }
        public Nullable<int> km { get; set; }
        public string tahmini_sure { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guzergah_Arayol> Guzergah_Arayol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guzergah_Tesis> Guzergah_Tesis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sefer> Sefer { get; set; }
    }
}
