//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilet_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guzergah_Arayol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guzergah_Arayol()
        {
            this.Sefer_Arayol = new HashSet<Sefer_Arayol>();
        }
    
        public int guzergah_arayol_id { get; set; }
        public Nullable<int> guzergah_id { get; set; }
        public Nullable<int> kontenjan { get; set; }
        public Nullable<decimal> ucret { get; set; }
        public string arayol { get; set; }
    
        public virtual Guzergah Guzergah { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sefer_Arayol> Sefer_Arayol { get; set; }
    }
}
