//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilet_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILLER_MESAFE
    {
        public string IL_ADI { get; set; }
        public Nullable<int> ADANA { get; set; }
        public Nullable<int> ADIYAMAN { get; set; }
        public Nullable<int> AFYON { get; set; }
        public Nullable<int> AĞRI { get; set; }
        public Nullable<int> AMASYA { get; set; }
        public Nullable<int> ANKARA { get; set; }
        public Nullable<int> ANTALYA { get; set; }
        public Nullable<int> ARTVİN { get; set; }
        public Nullable<int> AYDIN { get; set; }
        public Nullable<int> BALIKESİR { get; set; }
        public Nullable<int> BİLECİK { get; set; }
        public Nullable<int> BİNGÖL { get; set; }
        public Nullable<int> BİTLİS { get; set; }
        public Nullable<int> BOLU { get; set; }
        public Nullable<int> BURDUR { get; set; }
        public Nullable<int> BURSA { get; set; }
        public Nullable<int> ÇANAKKALE { get; set; }
        public Nullable<int> ÇANKIRI { get; set; }
        public Nullable<int> ÇORUM { get; set; }
        public Nullable<int> DENİZLİ { get; set; }
        public Nullable<int> DİYARBAKIR { get; set; }
        public Nullable<int> EDİRNE { get; set; }
        public Nullable<int> ELAZIĞ { get; set; }
        public Nullable<int> ERZİNCAN { get; set; }
        public Nullable<int> ERZURUM { get; set; }
        public Nullable<int> ESKİŞEHİR { get; set; }
        public Nullable<int> GAZİANTEP { get; set; }
        public Nullable<int> GİRESUN { get; set; }
        public Nullable<int> GÜMÜŞHANE { get; set; }
        public Nullable<int> HAKKARİ { get; set; }
        public Nullable<int> HATAY { get; set; }
        public Nullable<int> ISPARTA { get; set; }
        public Nullable<int> İÇEL { get; set; }
        public Nullable<int> İSTANBUL { get; set; }
        public Nullable<int> İZMİR { get; set; }
        public Nullable<int> KARS { get; set; }
        public Nullable<int> KASTAMONU { get; set; }
        public Nullable<int> KAYSERİ { get; set; }
        public Nullable<int> KIRKLARELİ { get; set; }
        public Nullable<int> KIRŞEHİR { get; set; }
        public Nullable<int> KOCAELİ { get; set; }
        public Nullable<int> KONYA { get; set; }
        public Nullable<int> KÜTAHYA { get; set; }
        public Nullable<int> MALATYA { get; set; }
        public Nullable<int> MANİSA { get; set; }
        public Nullable<int> KAHRAMANMARAŞ { get; set; }
        public Nullable<int> MARDİN { get; set; }
        public Nullable<int> MUĞLA { get; set; }
        public Nullable<int> MUŞ { get; set; }
        public Nullable<int> NEVŞEHİR { get; set; }
        public Nullable<int> NİĞDE { get; set; }
        public Nullable<int> ORDU { get; set; }
        public Nullable<int> RİZE { get; set; }
        public Nullable<int> SAKARYA { get; set; }
        public Nullable<int> SAMSUN { get; set; }
        public Nullable<int> SİİRT { get; set; }
        public Nullable<int> SİNOP { get; set; }
        public Nullable<int> SİVAS { get; set; }
        public Nullable<int> TEKİRDAĞ { get; set; }
        public Nullable<int> TOKAT { get; set; }
        public Nullable<int> TRABZON { get; set; }
        public Nullable<int> TUNCELİ { get; set; }
        public Nullable<int> ŞANLIURFA { get; set; }
        public Nullable<int> UŞAK { get; set; }
        public Nullable<int> VAN { get; set; }
        public Nullable<int> YOZGAT { get; set; }
        public Nullable<int> ZONGULDAK { get; set; }
        public Nullable<int> AKSARAY { get; set; }
        public Nullable<int> BAYBURT { get; set; }
        public Nullable<int> KARAMAN { get; set; }
        public Nullable<int> KIRIKKALE { get; set; }
        public Nullable<int> BATMAN { get; set; }
        public Nullable<int> ŞIRNAK { get; set; }
        public Nullable<int> BARTIN { get; set; }
        public Nullable<int> ARDAHAN { get; set; }
        public Nullable<int> IĞDIR { get; set; }
        public Nullable<int> YALOVA { get; set; }
        public Nullable<int> KARABÜK { get; set; }
        public Nullable<int> KİLİS { get; set; }
        public Nullable<int> OSMANİYE { get; set; }
        public Nullable<int> DÜZCE { get; set; }
    }
}
