//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilet_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otobus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Otobus()
        {
            this.Otobus_Detay = new HashSet<Otobus_Detay>();
            this.Otobus_Ozellik = new HashSet<Otobus_Ozellik>();
            this.Sefer = new HashSet<Sefer>();
        }
    
        public int otobus_id { get; set; }
        public Nullable<int> marka_kod { get; set; }
        public Nullable<int> model_kod { get; set; }
        public Nullable<int> koltuk_sayisi { get; set; }
        public string koltuk_tipi { get; set; }
        public string plaka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Otobus_Detay> Otobus_Detay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Otobus_Ozellik> Otobus_Ozellik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sefer> Sefer { get; set; }
    }
}
