//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilet_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otobus_Detay
    {
        public int otobus_detay_id { get; set; }
        public Nullable<int> otobus_id { get; set; }
        public Nullable<int> sofor_1_personel_id { get; set; }
        public Nullable<int> sofor_2_personel_id { get; set; }
        public Nullable<int> muavin_id { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string saat { get; set; }
        public Nullable<int> guzergah_id { get; set; }
    
        public virtual Otobus Otobus { get; set; }
    }
}
