//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilet_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otobus_Ozellik
    {
        public int otobus_ozellik_id { get; set; }
        public Nullable<int> ozellik_kod { get; set; }
        public Nullable<int> otobus_id { get; set; }
    
        public virtual Otobus Otobus { get; set; }
    }
}
