//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilet_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personel()
        {
            this.Bilet = new HashSet<Bilet>();
            this.Kullanici = new HashSet<Kullanici>();
            this.Rezerve = new HashSet<Rezerve>();
        }
    
        public int personel_id { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string TC { get; set; }
        public Nullable<int> bolum_kod { get; set; }
        public Nullable<int> gorev_kod { get; set; }
        public Nullable<int> cinsiyet_kod { get; set; }
        public string tel { get; set; }
        public string adresi { get; set; }
        public Nullable<int> yer_kod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bilet> Bilet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanici> Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezerve> Rezerve { get; set; }
    }
}
