//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilet_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezerve
    {
        public int rezerve_id { get; set; }
        public Nullable<System.DateTime> rezerve_tarihi { get; set; }
        public Nullable<int> rezerve_kod { get; set; }
        public Nullable<int> sefer_id { get; set; }
        public Nullable<int> rezerve_eden_kisi_id { get; set; }
        public Nullable<int> Koltuk_No { get; set; }
        public Nullable<int> yolcu_id { get; set; }
        public string kalkis { get; set; }
        public string varis { get; set; }
    
        public virtual Personel Personel { get; set; }
        public virtual Sefer Sefer { get; set; }
        public virtual Yolcu Yolcu { get; set; }
    }
}
