//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilet_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol_Servis
    {
        public int rol_servis_id { get; set; }
        public Nullable<int> rol_id { get; set; }
        public Nullable<int> servis_id { get; set; }
    
        public virtual Roller Roller { get; set; }
        public virtual Servis Servis { get; set; }
    }
}
