//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilet_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sefer_Arayol
    {
        public int sefer_arayol_id { get; set; }
        public Nullable<int> guzergah_arayol_id { get; set; }
        public Nullable<int> sefer_id { get; set; }
    
        public virtual Guzergah_Arayol Guzergah_Arayol { get; set; }
        public virtual Sefer Sefer { get; set; }
    }
}
