//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilet_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tesis
    {
        public int tesis_id { get; set; }
        public string adi { get; set; }
        public string adresi { get; set; }
        public string tel { get; set; }
        public string aciklama { get; set; }
    }
}
