//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilet_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yolcu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yolcu()
        {
            this.Bilet = new HashSet<Bilet>();
            this.Rezerve = new HashSet<Rezerve>();
        }
    
        public int yolcu_id { get; set; }
        public string adi_soyadi { get; set; }
        public string Tel { get; set; }
        public Nullable<bool> uyemi { get; set; }
        public string e_posta { get; set; }
        public Nullable<int> cinsiyet_kod { get; set; }
        public Nullable<long> TC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bilet> Bilet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezerve> Rezerve { get; set; }
    }
}
